feat(deps): Bump singer-sdk from 0.44.0 to 0.45.10 (#208)
Bumps [singer-sdk](https://github.com/meltano/sdk) from 0.44.0 to
0.45.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/releases">singer-sdk's
releases</a>.</em></p>
<blockquote>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
<h2>v0.45.6 (2025-04-11)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2961">#2961</a>
Conform <code>NaN</code>, <code>Infinity</code> and
<code>-Infinity</code> to null values</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2960">#2960</a>
Documented using <code>default=str</code> with <code>json.dumps</code>
in stream maps</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2955">#2955</a>
Documented the <code>ignore_parent_replication_key</code> stream
attribute</li>
</ul>
<h2>v0.45.5 (2025-04-04)</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/blob/main/CHANGELOG.md">singer-sdk's
changelog</a>.</em></p>
<blockquote>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
<h2>v0.45.6 (2025-04-11)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2961">#2961</a>
Conform <code>NaN</code>, <code>Infinity</code> and
<code>-Infinity</code> to null values</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2960">#2960</a>
Documented using <code>default=str</code> with <code>json.dumps</code>
in stream maps</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2955">#2955</a>
Documented the <code>ignore_parent_replication_key</code> stream
attribute</li>
</ul>
<h2>v0.45.5 (2025-04-04)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2952">#2952</a>
Adapt field schema type to <code>string</code> when transformed with
stream maps using <code>json.dumps</code></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/meltano/sdk/commit/aa54e2593eb1c4abf6303a6b75d7a7979f854a14"><code>aa54e25</code></a>
chore: Release v0.45.10 (<a
href="https://redirect.github.com/meltano/sdk/issues/2979">#2979</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/65575b5f72c9c3a69886a3805a07a61b7a72eb90"><code>65575b5</code></a>
fix: Restore private <code>_http_headers</code> attribute of REST
streams (<a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/1f401b90acb7f75296c5b800936625ffd23c9a47"><code>1f401b9</code></a>
chore: Use <code>--no-color</code> flag for griffe</li>
<li><a
href="https://github.com/meltano/sdk/commit/80bd614106c02c84dc44d9ba9918de1d1251510b"><code>80bd614</code></a>
chore: Release v0.45.9 (<a
href="https://redirect.github.com/meltano/sdk/issues/2976">#2976</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/42c26dd3354fdb776315e6ecc650e2b870628847"><code>42c26dd</code></a>
fix: Update cookiecutter templates (<a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/72939f2a371296681dff595ab9ba32a5dfa1b007"><code>72939f2</code></a>
fix: Do not log a warning if <code>null</code> cannot be appended to
schema types (<a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/986a745edc8bda1347d147356649b02785900d83"><code>986a745</code></a>
fix: Recognize <code>oneOf</code> fields in Singer schema helpers (<a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/b761e02d6a5272035c213037d2e59278b6662509"><code>b761e02</code></a>
chore: Release v0.45.8 (<a
href="https://redirect.github.com/meltano/sdk/issues/2972">#2972</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/d7c7a816b6d490519c3d737241b384ebed8058b0"><code>d7c7a81</code></a>
chore: Expose <code>singer_sdk._singerlib.Catalog</code> for typing-only
code</li>
<li><a
href="https://github.com/meltano/sdk/commit/3c116d877d3ed9bfcaa70d7a639876efa13614a4"><code>3c116d8</code></a>
fix: <code>AttributeError: object has no attribute
'_requests_session'</code> when acces...</li>
<li>Additional commits viewable in <a
href="https://github.com/meltano/sdk/compare/v0.44.0...v0.45.10">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=singer-sdk&package-manager=pip&previous-version=0.44.0&new-version=0.45.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>